#!/usr/bin/env bash
set -Eeuo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
./lab.sh ready
go test ./...
go test -p=1 -tags=integration -count=3 -timeout=6m ./...
go test -p=1 -race -tags=integration -count=1 -timeout=6m ./...
go build ./...
